FROM golang:1.8.1

RUN \
  curl -s 'https://download.ceph.com/keys/release.asc' | apt-key add - && \
  echo deb http://download.ceph.com/debian-jewel/ jessie main > /etc/apt/sources.list.d/ceph.list && \
  apt-get update && \
  apt-get -my install gnupg && \
  apt-get -my install librados-dev librbd-dev && \
  rm -rf /var/lib/apt/lists/*
ADD . /go/src/github.com/jameseck/cephback
RUN \
  go get -u github.com/golang/dep/...
WORKDIR /go/src/github.com/jameseck/cephback
RUN \
  dep ensure -update && \
  go install

 #&& \
#  go get -d github.com/jameseck/cephback
