FROM golang:1.7.5

RUN \
  curl -s 'https://download.ceph.com/keys/release.asc' | apt-key add - && \
  echo deb http://download.ceph.com/debian-jewel/ jessie main > /etc/apt/sources.list.d/ceph.list && \
  apt-get update && \
  apt-get -y install librados-dev librbd-dev && \
  rm -rf /var/lib/apt/lists/*
ADD . /go/src/github.com/jameseck/cephback
WORKDIR /go/src/github.com/jameseck/cephback
RUN \
  go get k8s.io/client-go/kubernetes && \
  git -C /go/src/k8s.io/client-go checkout v2.0.0 && \
  go get && \
  go build
