
[[constraint]]
  branch = "master"
  name = "github.com/Sirupsen/logrus"

[[constraint]]
  branch = "master"
  name = "github.com/alexflint/go-filemutex"

[[constraint]]
  branch = "master"
  name = "github.com/ceph/go-ceph"

[[constraint]]
  branch = "master"
  name = "github.com/prometheus/client_golang"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/cobra"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/viper"

[[constraint]]
  name = "k8s.io/client-go"
  version = "v2.0.0"

[[override]]
  name = "github.com/ugorji/go"
  revision = "8c0409fcbb70099c748d71f714529204975f6c3f"
